config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :events, only: [:index]
  resources :photos, only: [:index]
  get 'about', to: "pages#about"

end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope {order("date ASC")}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :photo_album
end

app/models/photo_album.rb
class PhotoAlbum < ActiveRecord::Base
  default_scope {order("created_at DESC")}
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photo_albums = PhotoAlbum.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.haml
.container#event
  %h1.center Upcoming Events
  %section
    .table-responsive
      %table.table.table-striped
        %tr
          %th Event
          %th Date
          %th Time
          %th Description
          %th Drink Specials
        - @events.each do |event|
          %tr
            %td= event.title
            %td
              = event.date.strftime("%A %b %d, %Y")
            %td= event.time.strftime("%I:%M %p")
            %td= event.description
            %td= event.specials

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChateauRails</title>
  <link href='https://fonts.googleapis.com/css?family=IM+Fell+English+SC|Raleway' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>
<%= yield %>
<%= render 'shared/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<section>
		<h1 class="center fancy">History</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at porttitor lectus. Vivamus in condimentum ante. Ut finibus diam id consectetur accumsan. In ac ullamcorper enim, at congue lorem. Suspendisse blandit dictum congue. Maecenas a purus finibus, tincidunt lectus sed, feugiat augue. Morbi laoreet, est vel dignissim lacinia, mi lacus gravida urna, vitae placerat metus quam nec velit. Integer et consequat urna. Sed semper lectus eu lectus mollis, et fermentum ante mattis. Donec porta eros sit amet sem finibus, eget condimentum urna pharetra. Donec vel erat sed nibh vehicula dapibus. Sed tincidunt turpis vel ligula maximus, nec laoreet erat molestie. Nulla semper justo vel tellus ullamcorper, sed egestas risus commodo. Aenean convallis ipsum quis pharetra tempus. Pellentesque quis gravida justo.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at porttitor lectus. Vivamus in condimentum ante. Ut finibus diam id consectetur accumsan. In ac ullamcorper enim, at congue lorem. Suspendisse blandit dictum congue. Maecenas a purus finibus, tincidunt lectus sed, feugiat augue. Morbi laoreet, est vel dignissim lacinia, mi lacus gravida urna, vitae placerat metus quam nec velit. Integer et consequat urna. Sed semper lectus eu lectus mollis, et fermentum ante mattis. Donec porta eros sit amet sem finibus, eget condimentum urna pharetra. Donec vel erat sed nibh vehicula dapibus. Sed tincidunt turpis vel ligula maximus, nec laoreet erat molestie. Nulla semper justo vel tellus ullamcorper, sed egestas risus commodo. Aenean convallis ipsum quis pharetra tempus. Pellentesque quis gravida justo.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at porttitor lectus. Vivamus in condimentum ante. Ut finibus diam id consectetur accumsan. In ac ullamcorper enim, at congue lorem. Suspendisse blandit dictum congue. Maecenas a purus finibus, tincidunt lectus sed, feugiat augue. Morbi laoreet, est vel dignissim lacinia, mi lacus gravida urna, vitae placerat metus quam nec velit. Integer et consequat urna. Sed semper lectus eu lectus mollis, et fermentum ante mattis. Donec porta eros sit amet sem finibus, eget condimentum urna pharetra. Donec vel erat sed nibh vehicula dapibus. Sed tincidunt turpis vel ligula maximus, nec laoreet erat molestie. Nulla semper justo vel tellus ullamcorper, sed egestas risus commodo. Aenean convallis ipsum quis pharetra tempus. Pellentesque quis gravida justo.</p>
		<h1 class="center fancy">Staff</h1>
		<div id="staff">
			<h3 class="center fancy">Owners</h3>
				<ul class="center list-inline">
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Dave</li>
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Sue</li>
				</ul>
			<h3 class="center fancy">Bartenders</h3>
				<ul class="center list-inline">
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Danny</li>
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Sarah</li>
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Michael</li>
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />John</li>
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Lisa</li>
				</ul>
			<h3 class="center fancy">Servers</h3>
				<ul class="center list-inline">
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Mindy</li>
					<li><img class="staff_pic" src="http://fpoimg.com/100x100" /><br />Darren</li>
				</ul>
		</div>
	</section>
</div>

app/views/pages/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 3000
    })
  });
</script>
<section>
		<div class="jumbotron">
			<div class="carousel" data-ride="carousel">
					<div class="carousel-inner" role="listbox">
						<div class="item active">
              <%= image_tag("banner1.jpg", alt: "First slide image", class: "center-block") %>
						</div>
						<div class="item">
              <%= image_tag("banner2.jpg", alt: "Second slide image", class: "center-block") %>
						</div>
						<div class="item">
              <%= image_tag("banner3.jpg", alt: "Third slide image", class: "center-block") %>
						</div>
						<div class="item">
              <%= image_tag("banner4.jpg", alt: "Fourth slide image", class: "center-block") %>
						</div>
					</div>
			</div>
		</div>
	</section>
	<div class="container">
		<section>
			<div class="row info">
				<div class="col-sm-3">
					<h2 class="fancy center">Hours</h2>
						<ul>
							<li>Wednesday – 9PM – 2AM</li>
							<li>Friday – Event by Booking</li>
							<li>Saturday –Event by Booking</li>
						</ul>
				</div>
				<div class="col-sm-6">
					<h2 class="fancy center">Info</h2>
					<div id="container">
						<p class="center">Lawrence's hottest dance club! Join us on Wednesdays for Pride Night, Fridays for Retro Night, and Saturdays for dance parties! 9pm to 2am. Always 18 and up!</p>
					</div>
				</div>
				<div class="col-sm-3">
					<h2 class="fancy center">Specials</h2>
					<ul>
						<li>$4 Double Wells</li>
						<li>$2 Shot of the Week</li>
						<li>$3 Sangria</li>
					</ul>
				</div>
			</div>
		</section>

app/views/photos/index.html.haml
.container
  %section
    %h1.center#photo_head Photos
  - @photo_albums.each do |album|
    %section.album.clearfix
      %h2= album.title
      %ul
        - album.photos.each do |photo|
          %li
            = image_tag(photo.img_url, alt: photo.alt)

app/views/shared/_contact_modal.html.erb
<div class="modal fade" id="contactModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="submit" class="btn btn-default pull-right" data-dismiss="modal">Close</button>
				<h2 class="modal-title">Contact Us</h2>
			</div>
			<div class="modal-body">
				<div class="row">

          <div class="col-sm-5">
						<h2 class="fancy center">Wilde's Chateau 24</h2>

						<address class="center">
							2412 Iowa St <br>
							Lawrence, KS 66046
						</address>
						<a href="mailto:info@wildeschateau.com" class="center-a">info@wildeschateau.com</a>
						<a href="tel:785-856-1514" class="center-a">(785) 856-1514</a>
					</div>
          <!--mail form not functional, for display purposes only -->
          <div class="col-sm-7">
						<form action="#" method="post" role="form">
							<div class="form-group">
								<label for="name">Name</label>
								<input type="text" class="form-control" name="name" id="name" placeholder="Your Name">
							</div>
							<div class="form-group">
								<label for="email">Email address</label>
								<input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
							</div>
							<div class="form-group">
								<label for="subject">Subject</label>
								<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject of Email">
							</div>
							<div class="form-group">
								<label for="message">Message</label>
								<textarea class="form-control" rows="6" name="message" id="message" placeholder="Message"></textarea>
							</div>
								<input style="display: none;" type="text" name="address" id="address" placeholder="Humans: Ignore, do not fill out"></input>
							<button type="submit" class="btn send">Submit</button>
						</form>
					</div>

					</div><!--end row-->
				</div><!--end modal body-->

				<div class="modal-footer">
					<div id="modal_media">
						<ul id="modal_social">
							<li><a href="https://www.facebook.com/Chateau24" class="icon-facebook" id="modal_facebook"></a></li>
							<li><a href="https://plus.google.com/115184087779748309954/about?gl=us&hl=en" class="icon-googleplus" id="modal_googleplus"></a></li>
							<li><a href="https://twitter.com/Chateau24" class="icon-twitter" id="modal_twitter"></a></li>
							<li><a href="http://www.yelp.com/biz/wildes-chateau-24-lawrence" class="icon-yelp" id="modal_yelp"></a></li>
						</ul>
					</div>
				</div><!--end modal footer -->

		</div><!--end modal content-->
	</div><!--end modal dialog-->
</div>

app/views/shared/_footer.html.erb
<footer>
	<p class="center">&copy; <%=Time.now.year %> Wilde's Chateau</p>
</footer>
</div>

app/views/shared/_header.html.erb
<%= render 'shared/contact_modal' %>
<header>
  <div class="container">
		<div id="branding" class="clearfix">
		<a id="logo" href=<%= root_path %>>
      <%= image_tag("chateau-logo.jpg", class: "img-responsive pull-left") %>
			<h1 class="fancy">Wilde's Chateau <span id="emp">24</span></h1>
		</a>
		<div id="social_media">
			<ul>
				<li><a href="https://www.facebook.com/Chateau24" class="icon-facebook" id="facebook"></a></li>
				<li><a href="https://plus.google.com/115184087779748309954/about?gl=us&hl=en" class="icon-googleplus" id="googleplus"></a></li>
				<li><a href="https://twitter.com/Chateau24" class="icon-twitter" id="twitter"></a></li>
				<li><a href="http://www.yelp.com/biz/wildes-chateau-24-lawrence" class="icon-yelp" id="yelp"></a></li>
			</ul>
		</div>
	</div>
	</div>
	<!-- Static navbar -->
  <div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Photos", photos_path %></li>
					<li><%= link_to "About", about_path %></li>
          <li><a data-toggle="modal" href="#contactModal" class="contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </div>

</header>